---
title: Read Me - Getting and Cleaning Data
author: "Chad Mathews"
date: "Sunday, October 26, 2014"
output: html_document

# Getting and Cleaning Data

This repository contains information related to the function of the "run_analysis.R" script created as a requirement for the Coursera - Getting and Cleaning Data - course project. 

## Goals of "run_analysis.R"

The script will download and unzip data files realted to the "Human Activity Recognition Using Smartphones Data Set" . Source file found [here]. 

The function of the script accomplishes the following goals:

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement. 
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names. 
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

### NOTES:
The script will download the data set to the current working directory in R and unzip to the \\UCI HAR Dataset File.




[here]: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 